# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pinky' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Nuke'
  pod "Alamofire"
  pod 'SwiftyJSON'

  # Pods for Pinky

  target 'PinkyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PinkyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
